### ISSUE TITLE
Unknown Extension: http://hl7.org/fhir/StructureDefinition/bodysite-laterality

### ISSUE THREAD

**Issue by techintrorepo** [HL7/fetal_records#10]
URL value 'http://hl7.org/fhir/StructureDefinition/bodysite-laterality' does not resolve
The extension http://hl7.org/fhir/StructureDefinition/bodysite-laterality is unknown, and not allowed here
--

**Comment by techintrorepo** [comment]
@LilianMinne I'd rather leave it open for now. We may end up with doing profile of Observation and Condition but that's not in scope for now.

**Comment by LilianMinne** [comment]
@techintrorepo I removed the extension from the example
